// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUsK9V2NkewWUmsNMxsGY-DiaqJ319wpo',
    appId: '1:710826427351:web:d4d5481d75b51a43708192',
    messagingSenderId: '710826427351',
    projectId: 'init-together-db',
    authDomain: 'init-together-db.firebaseapp.com',
    storageBucket: 'init-together-db.appspot.com',
    measurementId: 'G-LEGB30R4SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEQ6zWPLR0DEUScRQIwUSCZxMD0RSb6EA',
    appId: '1:710826427351:android:c98a553e77349c8c708192',
    messagingSenderId: '710826427351',
    projectId: 'init-together-db',
    storageBucket: 'init-together-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgujdeYq8ZOhCiM65IvSMGW84cfLtLig8',
    appId: '1:710826427351:ios:c0aebb17dc791a5c708192',
    messagingSenderId: '710826427351',
    projectId: 'init-together-db',
    storageBucket: 'init-together-db.appspot.com',
    iosClientId: '710826427351-qnj1a6stahlhbvh73prrjur2hpdtob6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.initTogetherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgujdeYq8ZOhCiM65IvSMGW84cfLtLig8',
    appId: '1:710826427351:ios:c0aebb17dc791a5c708192',
    messagingSenderId: '710826427351',
    projectId: 'init-together-db',
    storageBucket: 'init-together-db.appspot.com',
    iosClientId: '710826427351-qnj1a6stahlhbvh73prrjur2hpdtob6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.initTogetherApp',
  );
}
